management:
  endpoints:
    web:
      base-path: /meta
      exposure.include: health, info, env
  endpoint:
    health.show-details: always

# Actuator info configuration
info:
  app:
    name: @project.name@
    description:  @project.description@
    version: @project.version@
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

spring:
  datasource:
    username: @database.username@
    password: @database.password@
    driver-class-name: @database.driver@    
    url: jdbc:postgresql://${DATABASE_HOST:@database.host@}:${DATABASE_PORT:@database.port@}/@database.name@?currentSchema=@database.schema@
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:db/liquibase/master-changelog.xml
